apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "Discord"
          drop:
            - type: Normal
            - message: snapshot becomes not ready to use
            - message: snapshot is marked as removed
            - message: lost track of the corresponding snapshot info inside volume engine
            - message: .*probe failed.*
    receivers:
      - name: "Home Assistant"
        webhook:
          endpoint: "${home_assistant_event_webhook}"
          headers:
            User-Agent: kube-event-exporter 1.0
          layout:
            subject: workbench
            event: "{{ .Type }}: ({{ .Reason }}) {{ .Message }}"
