apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-volume1-media
  namespace: personal
spec:
  volumeName: nas-volume1-media-personal
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-volume1-games
  namespace: personal
spec:
  volumeName: nas-volume1-personal-games
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 100Ti
---
